// Monthly Subscription
export const MONTHLY_LOADING = 'MONTHLY_LOADING';
export const ADD_MONTHLY = 'ADD_MONTHLY';
export const MONTHLY_FAILED = 'MONTHLY_FAILED';
// Session Subscription
export const SESSION_LOADING = 'SESSION_LOADING';
export const ADD_SESSION = 'ADD_SESSION';
export const SESSION_FAILED = 'SESSION_FAILED';
// Trainer
export const TRAINER_LOADING = 'TRAINER_LOADING';
export const ADD_TRAINER = 'ADD_TRAINER';
export const TRAINER_FAILED = 'TRAINER_FAILED';
// cart
export const ADD_TO_CART = 'ADD_TO_CART';
export const ADD_TO_CART_FAILURE = 'ADD_TO_CART_FAILURE';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
// payment
export const ADD_SELECTED_ITEM_FOR_PAYMENT = 'ADD_SELECTED_ITEM_FOR_PAYMENT';
export const REMOVE_SELECTED_ITEM_FOR_PAYMENT = 'REMOVE_SELECTED_ITEM_FOR_PAYMENT';
export const PROCESS_PAYMENT = 'PROCESS_PAYMENT';
export const PROCESS_PAYMENT_SUCCESS = 'PROCESS_PAYMENT_SUCCESS';
export const PROCESS_PAYMENT_FAILURE = 'PROCESS_PAYMENT_FAILURE';
export const BILLS_LOADING = 'BILLS_LOADING';
export const ADD_BILLS = 'ADD_BILLS';
export const BILLS_FAILED = 'BILLS_FAILED';
export const SET_BILL_TYPE = 'SET_BILL_TYPE';

// customer
export const SET_CUSTOMER_ID = 'SET_CUSTOMER_ID';
export const CUSTOMER_LOADING = 'CUSTOMER_LOADING';
export const CUSTOMER_FAILED = 'CUSTOMER_FAILED';
export const ADD_CUSTOMER = 'ADD_CUSTOMER';
export const LOGOUT = 'LOGOUT';
//attendance
export const ADD_ATTENDANCE_REQUEST = 'ADD_ATTENDANCE_REQUEST';
export const ADD_ATTENDANCE_SUCCESS = 'ADD_ATTENDANCE_SUCCESS';
export const ADD_ATTENDANCE_FAILURE = 'ADD_ATTENDANCE_FAILURE';

export const FETCH_ATTENDANCES_REQUEST = 'FETCH_ATTENDANCES_REQUEST';
export const FETCH_ATTENDANCES_SUCCESS = 'FETCH_ATTENDANCES_SUCCESS';
export const FETCH_ATTENDANCES_FAILURE = 'FETCH_ATTENDANCES_FAILURE';

export const FETCH_ATTENDANCES_BY_BILL_ID_REQUEST = 'FETCH_ATTENDANCES_BY_BILL_ID_REQUEST';
export const FETCH_ATTENDANCES_BY_BILL_ID_SUCCESS = 'FETCH_ATTENDANCES_BY_BILL_ID_SUCCESS';
export const FETCH_ATTENDANCES_BY_BILL_ID_FAILURE = 'FETCH_ATTENDANCES_BY_BILL_ID_FAILURE';



